javascript-modal
bernardino8/c0821-code-solutions pull request #47
Opened 2021-09-01 00:16 UTC by bernardino8

Uploading Kapture 2021-08-31 at 16.45.06.mp4…

2021-09-01 00:50 UTC, codingcodymiller requested changes
Great start, man! A couple notes for you:

2021-09-01 00:50 UTC, codingcodymiller commented on javascript-modal/main.js
>  openButton.onclick = function () {
You definitely shouldn't apply event handlers this way. Please use the `addEventListener` method I taught you, this method of applying event handlers is somewhat outdated.

2021-09-01 00:50 UTC, codingcodymiller commented on javascript-modal/main.js
> +  modalWindow.style.display = 'none';
When you assign values directly to properties of the `style` property on elements, you are creating inline styling, which is a big no-no. Instead, you should prepare classes in your stylesheet that you can add and remove as necessary.

2021-09-03 06:18 UTC, bernardino8 commented
https://user-images.githubusercontent.com/88168364/131959291-a565a2c4-65a5-4b0a-88f3-e17c5bc6549d.mp4
thought of using event delegation for this assignment but opted not to; wonder how it would like though

2021-09-03 16:05 UTC, codingcodymiller approved these changes
Nice work!! Since there isn't anything being dynamically generated in this, it wouldn't be a great opportunity for event delegation, but you can give it a shot for practice!

2021-09-03 16:54 UTC, merged